api_login_check:
    path: /api/login
    
api_login_refresh:
    path: /api/login/refresh

weather:
    resource:
        path: ../src/Weather/Infrastructure/Controller
        namespace: App\Weather\Infrastructure\Controller
    type: attribute

web_client:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'react.html.twig'
