api_login_check:
    path: /api/login_check
    
weather:
    resource:
        path: ../src/Weather/Infrastructure/Controller
        namespace: App\Weather\Infrastructure\Controller
    type: attribute
