services:
    App\Weather\Domain\Repository\WeatherRepositoryInterface:
        public: true
        class: App\Weather\Infrastructure\Repository\DoctrineWeatherRepository
        arguments:
            $entityManager: '@Doctrine\ORM\EntityManagerInterface'

    App\Weather\Domain\Query\WeatherQueryInterface:
        public: true
        class: App\Weather\Infrastructure\Query\DoctrineDBALWeatherQuery
        arguments:
            $connection: '@Doctrine\DBAL\Connection'

    App\Weather\Infrastructure\Service\ObtainWeatherAPI:
        public: true
        class: App\Tests\Stub\ObtainWeatherAPIStub
