on: push
  
jobs:
  qa:
    runs-on: ubuntu-22.04
    container: makeitlv/php:8.2.1
    services:
      database:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: app_test
          POSTGRES_USER: app
          POSTGRES_PASSWORD: '!ChangeMe!'
          POSTGRES_HOST: postgres
          POSTGRES_PORT: '5432'
    steps:
      - uses: actions/checkout@v3
      - name: Install DB requirements
        run: |
          apk add --no-cache --virtual .pgsql-deps postgresql-dev
          docker-php-ext-install -j$(nproc) pdo_pgsql
          apk add --no-cache --virtual .pgsql-rundeps so:libpq.so.5
          apk del .pgsql-deps
      - name: Install project packages
        run: |
          curl --show-error --silent "https://getcomposer.org/installer" | php
          php composer.phar install --ignore-platform-reqs --no-ansi --no-interaction --no-scripts
          php composer.phar dump-autoload --optimize --classmap-authoritative
          php composer.phar check-platform-reqs
      - name: Test
        run: |
          php -d memory_limit=-1 ./bin/console lexik:jwt:generate-keypair --env=test --skip-if-exists --quiet
          php -d memory_limit=-1 ./bin/console doctrine:database:create --env=test --if-not-exists
          php -d memory_limit=-1 ./bin/console doctrine:schema:drop --env=test --force
          php -d memory_limit=-1 ./bin/console doctrine:schema:create --env=test
          php -d memory_limit=-1 ./bin/console cache:warmup --env=test
          php -d memory_limit=-1 ./bin/phpunit
